package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FasAccountinfo generated by hbm2java
 */
public class FasAccountinfo implements java.io.Serializable {

	private Integer id;
	private FasBankinfo fasBankinfo;
	private FasSubjectinfo fasSubjectinfo;
	private String aiType;
	private String aiName;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasAccountinfo() {
	}

	public FasAccountinfo(FasBankinfo fasBankinfo,
			FasSubjectinfo fasSubjectinfo, String aiType, String aiName,
			int empId, char delStatus) {
		this.fasBankinfo = fasBankinfo;
		this.fasSubjectinfo = fasSubjectinfo;
		this.aiType = aiType;
		this.aiName = aiName;
		this.empId = empId;
		this.delStatus = delStatus;
	}

	public FasAccountinfo(FasBankinfo fasBankinfo,
			FasSubjectinfo fasSubjectinfo, String aiType, String aiName,
			int empId, Date updateDate, Date createDate, char delStatus) {
		this.fasBankinfo = fasBankinfo;
		this.fasSubjectinfo = fasSubjectinfo;
		this.aiType = aiType;
		this.aiName = aiName;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FasBankinfo getFasBankinfo() {
		return this.fasBankinfo;
	}

	public void setFasBankinfo(FasBankinfo fasBankinfo) {
		this.fasBankinfo = fasBankinfo;
	}

	public FasSubjectinfo getFasSubjectinfo() {
		return this.fasSubjectinfo;
	}

	public void setFasSubjectinfo(FasSubjectinfo fasSubjectinfo) {
		this.fasSubjectinfo = fasSubjectinfo;
	}

	public String getAiType() {
		return this.aiType;
	}

	public void setAiType(String aiType) {
		this.aiType = aiType;
	}

	public String getAiName() {
		return this.aiName;
	}

	public void setAiName(String aiName) {
		this.aiName = aiName;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
