package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasBillbook generated by hbm2java
 */
public class FasBillbook implements java.io.Serializable {

	private Integer id;
	private FasSubjectinfo fasSubjectinfo;
	private Date billbookDate;
	private String billbookNumber;
	private BigDecimal billbookDm;
	private BigDecimal billbookLm;
	private char billbookSub;
	private int billbookHp;
	private String billbookFormat;
	private String billbookSum;
	private char delStatus;

	public FasBillbook() {
	}

	public FasBillbook(FasSubjectinfo fasSubjectinfo, Date billbookDate,
			String billbookNumber, BigDecimal billbookDm,
			BigDecimal billbookLm, char billbookSub, int billbookHp,
			String billbookFormat, char delStatus) {
		this.fasSubjectinfo = fasSubjectinfo;
		this.billbookDate = billbookDate;
		this.billbookNumber = billbookNumber;
		this.billbookDm = billbookDm;
		this.billbookLm = billbookLm;
		this.billbookSub = billbookSub;
		this.billbookHp = billbookHp;
		this.billbookFormat = billbookFormat;
		this.delStatus = delStatus;
	}

	public FasBillbook(FasSubjectinfo fasSubjectinfo, Date billbookDate,
			String billbookNumber, BigDecimal billbookDm,
			BigDecimal billbookLm, char billbookSub, int billbookHp,
			String billbookFormat, String billbookSum, char delStatus) {
		this.fasSubjectinfo = fasSubjectinfo;
		this.billbookDate = billbookDate;
		this.billbookNumber = billbookNumber;
		this.billbookDm = billbookDm;
		this.billbookLm = billbookLm;
		this.billbookSub = billbookSub;
		this.billbookHp = billbookHp;
		this.billbookFormat = billbookFormat;
		this.billbookSum = billbookSum;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FasSubjectinfo getFasSubjectinfo() {
		return this.fasSubjectinfo;
	}

	public void setFasSubjectinfo(FasSubjectinfo fasSubjectinfo) {
		this.fasSubjectinfo = fasSubjectinfo;
	}

	public Date getBillbookDate() {
		return this.billbookDate;
	}

	public void setBillbookDate(Date billbookDate) {
		this.billbookDate = billbookDate;
	}

	public String getBillbookNumber() {
		return this.billbookNumber;
	}

	public void setBillbookNumber(String billbookNumber) {
		this.billbookNumber = billbookNumber;
	}

	public BigDecimal getBillbookDm() {
		return this.billbookDm;
	}

	public void setBillbookDm(BigDecimal billbookDm) {
		this.billbookDm = billbookDm;
	}

	public BigDecimal getBillbookLm() {
		return this.billbookLm;
	}

	public void setBillbookLm(BigDecimal billbookLm) {
		this.billbookLm = billbookLm;
	}

	public char getBillbookSub() {
		return this.billbookSub;
	}

	public void setBillbookSub(char billbookSub) {
		this.billbookSub = billbookSub;
	}

	public int getBillbookHp() {
		return this.billbookHp;
	}

	public void setBillbookHp(int billbookHp) {
		this.billbookHp = billbookHp;
	}

	public String getBillbookFormat() {
		return this.billbookFormat;
	}

	public void setBillbookFormat(String billbookFormat) {
		this.billbookFormat = billbookFormat;
	}

	public String getBillbookSum() {
		return this.billbookSum;
	}

	public void setBillbookSum(String billbookSum) {
		this.billbookSum = billbookSum;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
