package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FasBiscwage generated by hbm2java
 */
public class FasBiscwage implements java.io.Serializable {

	private Integer id;
	private int biscDepartmentId;
	private int biscMajorId;
	private long biscWageMon;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;
	private Set fasWageverifies = new HashSet(0);

	public FasBiscwage() {
	}

	public FasBiscwage(int biscDepartmentId, int biscMajorId, long biscWageMon,
			int empId, char delStatus) {
		this.biscDepartmentId = biscDepartmentId;
		this.biscMajorId = biscMajorId;
		this.biscWageMon = biscWageMon;
		this.empId = empId;
		this.delStatus = delStatus;
	}

	public FasBiscwage(int biscDepartmentId, int biscMajorId, long biscWageMon,
			int empId, Date updateDate, Date createDate, char delStatus,
			Set fasWageverifies) {
		this.biscDepartmentId = biscDepartmentId;
		this.biscMajorId = biscMajorId;
		this.biscWageMon = biscWageMon;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
		this.fasWageverifies = fasWageverifies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getBiscDepartmentId() {
		return this.biscDepartmentId;
	}

	public void setBiscDepartmentId(int biscDepartmentId) {
		this.biscDepartmentId = biscDepartmentId;
	}

	public int getBiscMajorId() {
		return this.biscMajorId;
	}

	public void setBiscMajorId(int biscMajorId) {
		this.biscMajorId = biscMajorId;
	}

	public long getBiscWageMon() {
		return this.biscWageMon;
	}

	public void setBiscWageMon(long biscWageMon) {
		this.biscWageMon = biscWageMon;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

	public Set getFasWageverifies() {
		return this.fasWageverifies;
	}

	public void setFasWageverifies(Set fasWageverifies) {
		this.fasWageverifies = fasWageverifies;
	}

}
