package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasCopeinfo generated by hbm2java
 */
public class FasCopeinfo implements java.io.Serializable {

	private Integer id;
	private int copeinfoOi;
	private String copeinfoGt;
	private BigDecimal copeinfoGm;
	private BigDecimal copeinfoOa;
	private BigDecimal copeinfoSm;
	private char copeinfoFm;
	private int copeinfoAm;
	private String copeinfoRemark;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasCopeinfo() {
	}

	public FasCopeinfo(int copeinfoOi, String copeinfoGt,
			BigDecimal copeinfoGm, BigDecimal copeinfoSm, char copeinfoFm,
			int copeinfoAm, int empId, Date createDate, char delStatus) {
		this.copeinfoOi = copeinfoOi;
		this.copeinfoGt = copeinfoGt;
		this.copeinfoGm = copeinfoGm;
		this.copeinfoSm = copeinfoSm;
		this.copeinfoFm = copeinfoFm;
		this.copeinfoAm = copeinfoAm;
		this.empId = empId;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public FasCopeinfo(int copeinfoOi, String copeinfoGt,
			BigDecimal copeinfoGm, BigDecimal copeinfoOa,
			BigDecimal copeinfoSm, char copeinfoFm, int copeinfoAm,
			String copeinfoRemark, int empId, Date updateDate, Date createDate,
			char delStatus) {
		this.copeinfoOi = copeinfoOi;
		this.copeinfoGt = copeinfoGt;
		this.copeinfoGm = copeinfoGm;
		this.copeinfoOa = copeinfoOa;
		this.copeinfoSm = copeinfoSm;
		this.copeinfoFm = copeinfoFm;
		this.copeinfoAm = copeinfoAm;
		this.copeinfoRemark = copeinfoRemark;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCopeinfoOi() {
		return this.copeinfoOi;
	}

	public void setCopeinfoOi(int copeinfoOi) {
		this.copeinfoOi = copeinfoOi;
	}

	public String getCopeinfoGt() {
		return this.copeinfoGt;
	}

	public void setCopeinfoGt(String copeinfoGt) {
		this.copeinfoGt = copeinfoGt;
	}

	public BigDecimal getCopeinfoGm() {
		return this.copeinfoGm;
	}

	public void setCopeinfoGm(BigDecimal copeinfoGm) {
		this.copeinfoGm = copeinfoGm;
	}

	public BigDecimal getCopeinfoOa() {
		return this.copeinfoOa;
	}

	public void setCopeinfoOa(BigDecimal copeinfoOa) {
		this.copeinfoOa = copeinfoOa;
	}

	public BigDecimal getCopeinfoSm() {
		return this.copeinfoSm;
	}

	public void setCopeinfoSm(BigDecimal copeinfoSm) {
		this.copeinfoSm = copeinfoSm;
	}

	public char getCopeinfoFm() {
		return this.copeinfoFm;
	}

	public void setCopeinfoFm(char copeinfoFm) {
		this.copeinfoFm = copeinfoFm;
	}

	public int getCopeinfoAm() {
		return this.copeinfoAm;
	}

	public void setCopeinfoAm(int copeinfoAm) {
		this.copeinfoAm = copeinfoAm;
	}

	public String getCopeinfoRemark() {
		return this.copeinfoRemark;
	}

	public void setCopeinfoRemark(String copeinfoRemark) {
		this.copeinfoRemark = copeinfoRemark;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
