package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FasCheckinfo generated by hbm2java
 */
public class FasCheckinfo implements java.io.Serializable {

	private Integer id;
	private FasBankinfo fasBankinfo;
	private Date ciDate;
	private String ciIncept;
	private String ciStop;
	private Character ciStatus;
	private Date ciHxstatus;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasCheckinfo() {
	}

	public FasCheckinfo(FasBankinfo fasBankinfo, Date ciDate, String ciIncept,
			String ciStop, int empId, Date createDate, char delStatus) {
		this.fasBankinfo = fasBankinfo;
		this.ciDate = ciDate;
		this.ciIncept = ciIncept;
		this.ciStop = ciStop;
		this.empId = empId;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public FasCheckinfo(FasBankinfo fasBankinfo, Date ciDate, String ciIncept,
			String ciStop, Character ciStatus, Date ciHxstatus, int empId,
			Date updateDate, Date createDate, char delStatus) {
		this.fasBankinfo = fasBankinfo;
		this.ciDate = ciDate;
		this.ciIncept = ciIncept;
		this.ciStop = ciStop;
		this.ciStatus = ciStatus;
		this.ciHxstatus = ciHxstatus;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FasBankinfo getFasBankinfo() {
		return this.fasBankinfo;
	}

	public void setFasBankinfo(FasBankinfo fasBankinfo) {
		this.fasBankinfo = fasBankinfo;
	}

	public Date getCiDate() {
		return this.ciDate;
	}

	public void setCiDate(Date ciDate) {
		this.ciDate = ciDate;
	}

	public String getCiIncept() {
		return this.ciIncept;
	}

	public void setCiIncept(String ciIncept) {
		this.ciIncept = ciIncept;
	}

	public String getCiStop() {
		return this.ciStop;
	}

	public void setCiStop(String ciStop) {
		this.ciStop = ciStop;
	}

	public Character getCiStatus() {
		return this.ciStatus;
	}

	public void setCiStatus(Character ciStatus) {
		this.ciStatus = ciStatus;
	}

	public Date getCiHxstatus() {
		return this.ciHxstatus;
	}

	public void setCiHxstatus(Date ciHxstatus) {
		this.ciHxstatus = ciHxstatus;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
