package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasEvectioninfo generated by hbm2java
 */
public class FasEvectioninfo implements java.io.Serializable {

	private int id;
	private int employeesId;
	private Date evectionTime;
	private String evectionPlace;
	private BigDecimal evectionMoney;
	private String evectionRemark;
	private BigDecimal evectionPm;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasEvectioninfo() {
	}

	public FasEvectioninfo(int id, int employeesId, Date evectionTime,
			String evectionPlace, int empId, char delStatus) {
		this.id = id;
		this.employeesId = employeesId;
		this.evectionTime = evectionTime;
		this.evectionPlace = evectionPlace;
		this.empId = empId;
		this.delStatus = delStatus;
	}

	public FasEvectioninfo(int id, int employeesId, Date evectionTime,
			String evectionPlace, BigDecimal evectionMoney,
			String evectionRemark, BigDecimal evectionPm, int empId,
			Date updateDate, Date createDate, char delStatus) {
		this.id = id;
		this.employeesId = employeesId;
		this.evectionTime = evectionTime;
		this.evectionPlace = evectionPlace;
		this.evectionMoney = evectionMoney;
		this.evectionRemark = evectionRemark;
		this.evectionPm = evectionPm;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEmployeesId() {
		return this.employeesId;
	}

	public void setEmployeesId(int employeesId) {
		this.employeesId = employeesId;
	}

	public Date getEvectionTime() {
		return this.evectionTime;
	}

	public void setEvectionTime(Date evectionTime) {
		this.evectionTime = evectionTime;
	}

	public String getEvectionPlace() {
		return this.evectionPlace;
	}

	public void setEvectionPlace(String evectionPlace) {
		this.evectionPlace = evectionPlace;
	}

	public BigDecimal getEvectionMoney() {
		return this.evectionMoney;
	}

	public void setEvectionMoney(BigDecimal evectionMoney) {
		this.evectionMoney = evectionMoney;
	}

	public String getEvectionRemark() {
		return this.evectionRemark;
	}

	public void setEvectionRemark(String evectionRemark) {
		this.evectionRemark = evectionRemark;
	}

	public BigDecimal getEvectionPm() {
		return this.evectionPm;
	}

	public void setEvectionPm(BigDecimal evectionPm) {
		this.evectionPm = evectionPm;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
