package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasFloorId generated by hbm2java
 */
public class FasFloorId implements java.io.Serializable {

	private Integer id;
	private String floorTypename;
	private String floorName;
	private String floorCompany;
	private String floorHiretype;
	private BigDecimal floorPrice;
	private BigDecimal floorApply;
	private Integer floorApplyEmpid;
	private Date floorBegintime;
	private Date floorEndtime;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasFloorId() {
	}

	public FasFloorId(String floorTypename, String floorName,
			String floorCompany, BigDecimal floorPrice, BigDecimal floorApply,
			int empId, Date updateDate, char delStatus) {
		this.floorTypename = floorTypename;
		this.floorName = floorName;
		this.floorCompany = floorCompany;
		this.floorPrice = floorPrice;
		this.floorApply = floorApply;
		this.empId = empId;
		this.updateDate = updateDate;
		this.delStatus = delStatus;
	}

	public FasFloorId(Integer id, String floorTypename, String floorName,
			String floorCompany, String floorHiretype, BigDecimal floorPrice,
			BigDecimal floorApply, Integer floorApplyEmpid,
			Date floorBegintime, Date floorEndtime, int empId, Date updateDate,
			Date createDate, char delStatus) {
		this.id = id;
		this.floorTypename = floorTypename;
		this.floorName = floorName;
		this.floorCompany = floorCompany;
		this.floorHiretype = floorHiretype;
		this.floorPrice = floorPrice;
		this.floorApply = floorApply;
		this.floorApplyEmpid = floorApplyEmpid;
		this.floorBegintime = floorBegintime;
		this.floorEndtime = floorEndtime;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFloorTypename() {
		return this.floorTypename;
	}

	public void setFloorTypename(String floorTypename) {
		this.floorTypename = floorTypename;
	}

	public String getFloorName() {
		return this.floorName;
	}

	public void setFloorName(String floorName) {
		this.floorName = floorName;
	}

	public String getFloorCompany() {
		return this.floorCompany;
	}

	public void setFloorCompany(String floorCompany) {
		this.floorCompany = floorCompany;
	}

	public String getFloorHiretype() {
		return this.floorHiretype;
	}

	public void setFloorHiretype(String floorHiretype) {
		this.floorHiretype = floorHiretype;
	}

	public BigDecimal getFloorPrice() {
		return this.floorPrice;
	}

	public void setFloorPrice(BigDecimal floorPrice) {
		this.floorPrice = floorPrice;
	}

	public BigDecimal getFloorApply() {
		return this.floorApply;
	}

	public void setFloorApply(BigDecimal floorApply) {
		this.floorApply = floorApply;
	}

	public Integer getFloorApplyEmpid() {
		return this.floorApplyEmpid;
	}

	public void setFloorApplyEmpid(Integer floorApplyEmpid) {
		this.floorApplyEmpid = floorApplyEmpid;
	}

	public Date getFloorBegintime() {
		return this.floorBegintime;
	}

	public void setFloorBegintime(Date floorBegintime) {
		this.floorBegintime = floorBegintime;
	}

	public Date getFloorEndtime() {
		return this.floorEndtime;
	}

	public void setFloorEndtime(Date floorEndtime) {
		this.floorEndtime = floorEndtime;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FasFloorId))
			return false;
		FasFloorId castOther = (FasFloorId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getFloorTypename() == castOther.getFloorTypename()) || (this
						.getFloorTypename() != null
						&& castOther.getFloorTypename() != null && this
						.getFloorTypename()
						.equals(castOther.getFloorTypename())))
				&& ((this.getFloorName() == castOther.getFloorName()) || (this
						.getFloorName() != null
						&& castOther.getFloorName() != null && this
						.getFloorName().equals(castOther.getFloorName())))
				&& ((this.getFloorCompany() == castOther.getFloorCompany()) || (this
						.getFloorCompany() != null
						&& castOther.getFloorCompany() != null && this
						.getFloorCompany().equals(castOther.getFloorCompany())))
				&& ((this.getFloorHiretype() == castOther.getFloorHiretype()) || (this
						.getFloorHiretype() != null
						&& castOther.getFloorHiretype() != null && this
						.getFloorHiretype()
						.equals(castOther.getFloorHiretype())))
				&& ((this.getFloorPrice() == castOther.getFloorPrice()) || (this
						.getFloorPrice() != null
						&& castOther.getFloorPrice() != null && this
						.getFloorPrice().equals(castOther.getFloorPrice())))
				&& ((this.getFloorApply() == castOther.getFloorApply()) || (this
						.getFloorApply() != null
						&& castOther.getFloorApply() != null && this
						.getFloorApply().equals(castOther.getFloorApply())))
				&& ((this.getFloorApplyEmpid() == castOther
						.getFloorApplyEmpid()) || (this.getFloorApplyEmpid() != null
						&& castOther.getFloorApplyEmpid() != null && this
						.getFloorApplyEmpid().equals(
								castOther.getFloorApplyEmpid())))
				&& ((this.getFloorBegintime() == castOther.getFloorBegintime()) || (this
						.getFloorBegintime() != null
						&& castOther.getFloorBegintime() != null && this
						.getFloorBegintime().equals(
								castOther.getFloorBegintime())))
				&& ((this.getFloorEndtime() == castOther.getFloorEndtime()) || (this
						.getFloorEndtime() != null
						&& castOther.getFloorEndtime() != null && this
						.getFloorEndtime().equals(castOther.getFloorEndtime())))
				&& (this.getEmpId() == castOther.getEmpId())
				&& ((this.getUpdateDate() == castOther.getUpdateDate()) || (this
						.getUpdateDate() != null
						&& castOther.getUpdateDate() != null && this
						.getUpdateDate().equals(castOther.getUpdateDate())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& (this.getDelStatus() == castOther.getDelStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getFloorTypename() == null ? 0 : this.getFloorTypename()
						.hashCode());
		result = 37 * result
				+ (getFloorName() == null ? 0 : this.getFloorName().hashCode());
		result = 37
				* result
				+ (getFloorCompany() == null ? 0 : this.getFloorCompany()
						.hashCode());
		result = 37
				* result
				+ (getFloorHiretype() == null ? 0 : this.getFloorHiretype()
						.hashCode());
		result = 37
				* result
				+ (getFloorPrice() == null ? 0 : this.getFloorPrice()
						.hashCode());
		result = 37
				* result
				+ (getFloorApply() == null ? 0 : this.getFloorApply()
						.hashCode());
		result = 37
				* result
				+ (getFloorApplyEmpid() == null ? 0 : this.getFloorApplyEmpid()
						.hashCode());
		result = 37
				* result
				+ (getFloorBegintime() == null ? 0 : this.getFloorBegintime()
						.hashCode());
		result = 37
				* result
				+ (getFloorEndtime() == null ? 0 : this.getFloorEndtime()
						.hashCode());
		result = 37 * result + this.getEmpId();
		result = 37
				* result
				+ (getUpdateDate() == null ? 0 : this.getUpdateDate()
						.hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result + this.getDelStatus();
		return result;
	}

}
