package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

/**
 * FasFloor generated by hbm2java
 */
public class FasFloor implements java.io.Serializable {

	private FasFloorId id;

	public FasFloor() {
	}

	public FasFloor(FasFloorId id) {
		this.id = id;
	}

	public FasFloorId getId() {
		return this.id;
	}

	public void setId(FasFloorId id) {
		this.id = id;
	}

}
