package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FasGerenalledger generated by hbm2java
 */
public class FasGerenalledger implements java.io.Serializable {

	private Integer id;
	private FasSubjectinfo fasSubjectinfo;
	private String subjectName;
	private String generalBd;
	private BigDecimal generalBb;
	private BigDecimal generalCa;
	private BigDecimal generalCr;
	private BigDecimal generalYa;
	private BigDecimal generalYr;
	private BigDecimal generalEb;
	private String generalSummary;

	public FasGerenalledger() {
	}

	public FasGerenalledger(FasSubjectinfo fasSubjectinfo, String subjectName,
			String generalBd, BigDecimal generalBb, BigDecimal generalCa,
			BigDecimal generalCr, BigDecimal generalYa, BigDecimal generalYr,
			BigDecimal generalEb) {
		this.fasSubjectinfo = fasSubjectinfo;
		this.subjectName = subjectName;
		this.generalBd = generalBd;
		this.generalBb = generalBb;
		this.generalCa = generalCa;
		this.generalCr = generalCr;
		this.generalYa = generalYa;
		this.generalYr = generalYr;
		this.generalEb = generalEb;
	}

	public FasGerenalledger(FasSubjectinfo fasSubjectinfo, String subjectName,
			String generalBd, BigDecimal generalBb, BigDecimal generalCa,
			BigDecimal generalCr, BigDecimal generalYa, BigDecimal generalYr,
			BigDecimal generalEb, String generalSummary) {
		this.fasSubjectinfo = fasSubjectinfo;
		this.subjectName = subjectName;
		this.generalBd = generalBd;
		this.generalBb = generalBb;
		this.generalCa = generalCa;
		this.generalCr = generalCr;
		this.generalYa = generalYa;
		this.generalYr = generalYr;
		this.generalEb = generalEb;
		this.generalSummary = generalSummary;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public FasSubjectinfo getFasSubjectinfo() {
		return this.fasSubjectinfo;
	}

	public void setFasSubjectinfo(FasSubjectinfo fasSubjectinfo) {
		this.fasSubjectinfo = fasSubjectinfo;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public String getGeneralBd() {
		return this.generalBd;
	}

	public void setGeneralBd(String generalBd) {
		this.generalBd = generalBd;
	}

	public BigDecimal getGeneralBb() {
		return this.generalBb;
	}

	public void setGeneralBb(BigDecimal generalBb) {
		this.generalBb = generalBb;
	}

	public BigDecimal getGeneralCa() {
		return this.generalCa;
	}

	public void setGeneralCa(BigDecimal generalCa) {
		this.generalCa = generalCa;
	}

	public BigDecimal getGeneralCr() {
		return this.generalCr;
	}

	public void setGeneralCr(BigDecimal generalCr) {
		this.generalCr = generalCr;
	}

	public BigDecimal getGeneralYa() {
		return this.generalYa;
	}

	public void setGeneralYa(BigDecimal generalYa) {
		this.generalYa = generalYa;
	}

	public BigDecimal getGeneralYr() {
		return this.generalYr;
	}

	public void setGeneralYr(BigDecimal generalYr) {
		this.generalYr = generalYr;
	}

	public BigDecimal getGeneralEb() {
		return this.generalEb;
	}

	public void setGeneralEb(BigDecimal generalEb) {
		this.generalEb = generalEb;
	}

	public String getGeneralSummary() {
		return this.generalSummary;
	}

	public void setGeneralSummary(String generalSummary) {
		this.generalSummary = generalSummary;
	}

}
