package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasReceiptinfo generated by hbm2java
 */
public class FasReceiptinfo implements java.io.Serializable {

	private Integer id;
	private String receiptType;
	private String receiptMode;
	private int clientId;
	private BigDecimal receiptMoney;
	private int empId;
	private String receiptRemark;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasReceiptinfo() {
	}

	public FasReceiptinfo(String receiptType, String receiptMode, int clientId,
			BigDecimal receiptMoney, int empId, String receiptRemark,
			char delStatus) {
		this.receiptType = receiptType;
		this.receiptMode = receiptMode;
		this.clientId = clientId;
		this.receiptMoney = receiptMoney;
		this.empId = empId;
		this.receiptRemark = receiptRemark;
		this.delStatus = delStatus;
	}

	public FasReceiptinfo(String receiptType, String receiptMode, int clientId,
			BigDecimal receiptMoney, int empId, String receiptRemark,
			Date updateDate, Date createDate, char delStatus) {
		this.receiptType = receiptType;
		this.receiptMode = receiptMode;
		this.clientId = clientId;
		this.receiptMoney = receiptMoney;
		this.empId = empId;
		this.receiptRemark = receiptRemark;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getReceiptType() {
		return this.receiptType;
	}

	public void setReceiptType(String receiptType) {
		this.receiptType = receiptType;
	}

	public String getReceiptMode() {
		return this.receiptMode;
	}

	public void setReceiptMode(String receiptMode) {
		this.receiptMode = receiptMode;
	}

	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public BigDecimal getReceiptMoney() {
		return this.receiptMoney;
	}

	public void setReceiptMoney(BigDecimal receiptMoney) {
		this.receiptMoney = receiptMoney;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public String getReceiptRemark() {
		return this.receiptRemark;
	}

	public void setReceiptRemark(String receiptRemark) {
		this.receiptRemark = receiptRemark;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
