package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FasSubjectinfo generated by hbm2java
 */
public class FasSubjectinfo implements java.io.Serializable {

	private Integer id;
	private String subjectName;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;
	private Set fasAccountinfos = new HashSet(0);
	private Set fasSuitcollections = new HashSet(0);
	private Set fasBillbooks = new HashSet(0);
	private Set fasGerenalledgers = new HashSet(0);

	public FasSubjectinfo() {
	}

	public FasSubjectinfo(String subjectName, int empId, char delStatus) {
		this.subjectName = subjectName;
		this.empId = empId;
		this.delStatus = delStatus;
	}

	public FasSubjectinfo(String subjectName, int empId, Date updateDate,
			Date createDate, char delStatus, Set fasAccountinfos,
			Set fasSuitcollections, Set fasBillbooks, Set fasGerenalledgers) {
		this.subjectName = subjectName;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
		this.fasAccountinfos = fasAccountinfos;
		this.fasSuitcollections = fasSuitcollections;
		this.fasBillbooks = fasBillbooks;
		this.fasGerenalledgers = fasGerenalledgers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

	public Set getFasAccountinfos() {
		return this.fasAccountinfos;
	}

	public void setFasAccountinfos(Set fasAccountinfos) {
		this.fasAccountinfos = fasAccountinfos;
	}

	public Set getFasSuitcollections() {
		return this.fasSuitcollections;
	}

	public void setFasSuitcollections(Set fasSuitcollections) {
		this.fasSuitcollections = fasSuitcollections;
	}

	public Set getFasBillbooks() {
		return this.fasBillbooks;
	}

	public void setFasBillbooks(Set fasBillbooks) {
		this.fasBillbooks = fasBillbooks;
	}

	public Set getFasGerenalledgers() {
		return this.fasGerenalledgers;
	}

	public void setFasGerenalledgers(Set fasGerenalledgers) {
		this.fasGerenalledgers = fasGerenalledgers;
	}

}
