package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasSuitcollection generated by hbm2java
 */
public class FasSuitcollection implements java.io.Serializable {

	private int id;
	private FasSubjectinfo fasSubjectinfo;
	private int orderId;
	private String suitciGt;
	private BigDecimal suitciGm;
	private BigDecimal suitciOa;
	private BigDecimal suitciSm;
	private char suitciFm;
	private int suitciMm;
	private int suitciAm;
	private String suitciRemark;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasSuitcollection() {
	}

	public FasSuitcollection(int id, FasSubjectinfo fasSubjectinfo,
			int orderId, String suitciGt, BigDecimal suitciGm,
			BigDecimal suitciSm, char suitciFm, int suitciMm, int suitciAm,
			char delStatus) {
		this.id = id;
		this.fasSubjectinfo = fasSubjectinfo;
		this.orderId = orderId;
		this.suitciGt = suitciGt;
		this.suitciGm = suitciGm;
		this.suitciSm = suitciSm;
		this.suitciFm = suitciFm;
		this.suitciMm = suitciMm;
		this.suitciAm = suitciAm;
		this.delStatus = delStatus;
	}

	public FasSuitcollection(int id, FasSubjectinfo fasSubjectinfo,
			int orderId, String suitciGt, BigDecimal suitciGm,
			BigDecimal suitciOa, BigDecimal suitciSm, char suitciFm,
			int suitciMm, int suitciAm, String suitciRemark, Date updateDate,
			Date createDate, char delStatus) {
		this.id = id;
		this.fasSubjectinfo = fasSubjectinfo;
		this.orderId = orderId;
		this.suitciGt = suitciGt;
		this.suitciGm = suitciGm;
		this.suitciOa = suitciOa;
		this.suitciSm = suitciSm;
		this.suitciFm = suitciFm;
		this.suitciMm = suitciMm;
		this.suitciAm = suitciAm;
		this.suitciRemark = suitciRemark;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public FasSubjectinfo getFasSubjectinfo() {
		return this.fasSubjectinfo;
	}

	public void setFasSubjectinfo(FasSubjectinfo fasSubjectinfo) {
		this.fasSubjectinfo = fasSubjectinfo;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getSuitciGt() {
		return this.suitciGt;
	}

	public void setSuitciGt(String suitciGt) {
		this.suitciGt = suitciGt;
	}

	public BigDecimal getSuitciGm() {
		return this.suitciGm;
	}

	public void setSuitciGm(BigDecimal suitciGm) {
		this.suitciGm = suitciGm;
	}

	public BigDecimal getSuitciOa() {
		return this.suitciOa;
	}

	public void setSuitciOa(BigDecimal suitciOa) {
		this.suitciOa = suitciOa;
	}

	public BigDecimal getSuitciSm() {
		return this.suitciSm;
	}

	public void setSuitciSm(BigDecimal suitciSm) {
		this.suitciSm = suitciSm;
	}

	public char getSuitciFm() {
		return this.suitciFm;
	}

	public void setSuitciFm(char suitciFm) {
		this.suitciFm = suitciFm;
	}

	public int getSuitciMm() {
		return this.suitciMm;
	}

	public void setSuitciMm(int suitciMm) {
		this.suitciMm = suitciMm;
	}

	public int getSuitciAm() {
		return this.suitciAm;
	}

	public void setSuitciAm(int suitciAm) {
		this.suitciAm = suitciAm;
	}

	public String getSuitciRemark() {
		return this.suitciRemark;
	}

	public void setSuitciRemark(String suitciRemark) {
		this.suitciRemark = suitciRemark;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
