package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * FasTenancy generated by hbm2java
 */
public class FasTenancy implements java.io.Serializable {

	private Integer id;
	private BigDecimal applyBankroll;
	private int applyMan;
	private String synopsis;
	private String linkman;
	private String linkmanPhone;
	private int createName;
	private char tenancyState;
	private int empId;
	private Date updateDate;
	private Date createDate;
	private char delStatus;

	public FasTenancy() {
	}

	public FasTenancy(BigDecimal applyBankroll, int applyMan, String linkman,
			String linkmanPhone, int createName, char tenancyState, int empId,
			char delStatus) {
		this.applyBankroll = applyBankroll;
		this.applyMan = applyMan;
		this.linkman = linkman;
		this.linkmanPhone = linkmanPhone;
		this.createName = createName;
		this.tenancyState = tenancyState;
		this.empId = empId;
		this.delStatus = delStatus;
	}

	public FasTenancy(BigDecimal applyBankroll, int applyMan, String synopsis,
			String linkman, String linkmanPhone, int createName,
			char tenancyState, int empId, Date updateDate, Date createDate,
			char delStatus) {
		this.applyBankroll = applyBankroll;
		this.applyMan = applyMan;
		this.synopsis = synopsis;
		this.linkman = linkman;
		this.linkmanPhone = linkmanPhone;
		this.createName = createName;
		this.tenancyState = tenancyState;
		this.empId = empId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.delStatus = delStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getApplyBankroll() {
		return this.applyBankroll;
	}

	public void setApplyBankroll(BigDecimal applyBankroll) {
		this.applyBankroll = applyBankroll;
	}

	public int getApplyMan() {
		return this.applyMan;
	}

	public void setApplyMan(int applyMan) {
		this.applyMan = applyMan;
	}

	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinkmanPhone() {
		return this.linkmanPhone;
	}

	public void setLinkmanPhone(String linkmanPhone) {
		this.linkmanPhone = linkmanPhone;
	}

	public int getCreateName() {
		return this.createName;
	}

	public void setCreateName(int createName) {
		this.createName = createName;
	}

	public char getTenancyState() {
		return this.tenancyState;
	}

	public void setTenancyState(char tenancyState) {
		this.tenancyState = tenancyState;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

}
