package com.lis.fas.entity;

// Generated 2015-5-16 11:45:34 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FasWageverify generated by hbm2java
 */
public class FasWageverify implements java.io.Serializable {

	private int id;
	private FasBiscwage fasBiscwage;
	private int employeeId;
	private BigDecimal superfluityWage;
	private BigDecimal recoupWage;
	private BigDecimal wageRevenue;
	private BigDecimal deservelyWage;
	private String wageRewark;
	private char delStatus;
	private BigDecimal bascWage;

	public FasWageverify() {
	}

	public FasWageverify(int id, FasBiscwage fasBiscwage, int employeeId,
			BigDecimal wageRevenue, BigDecimal deservelyWage, char delStatus,
			BigDecimal bascWage) {
		this.id = id;
		this.fasBiscwage = fasBiscwage;
		this.employeeId = employeeId;
		this.wageRevenue = wageRevenue;
		this.deservelyWage = deservelyWage;
		this.delStatus = delStatus;
		this.bascWage = bascWage;
	}

	public FasWageverify(int id, FasBiscwage fasBiscwage, int employeeId,
			BigDecimal superfluityWage, BigDecimal recoupWage,
			BigDecimal wageRevenue, BigDecimal deservelyWage,
			String wageRewark, char delStatus, BigDecimal bascWage) {
		this.id = id;
		this.fasBiscwage = fasBiscwage;
		this.employeeId = employeeId;
		this.superfluityWage = superfluityWage;
		this.recoupWage = recoupWage;
		this.wageRevenue = wageRevenue;
		this.deservelyWage = deservelyWage;
		this.wageRewark = wageRewark;
		this.delStatus = delStatus;
		this.bascWage = bascWage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public FasBiscwage getFasBiscwage() {
		return this.fasBiscwage;
	}

	public void setFasBiscwage(FasBiscwage fasBiscwage) {
		this.fasBiscwage = fasBiscwage;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public BigDecimal getSuperfluityWage() {
		return this.superfluityWage;
	}

	public void setSuperfluityWage(BigDecimal superfluityWage) {
		this.superfluityWage = superfluityWage;
	}

	public BigDecimal getRecoupWage() {
		return this.recoupWage;
	}

	public void setRecoupWage(BigDecimal recoupWage) {
		this.recoupWage = recoupWage;
	}

	public BigDecimal getWageRevenue() {
		return this.wageRevenue;
	}

	public void setWageRevenue(BigDecimal wageRevenue) {
		this.wageRevenue = wageRevenue;
	}

	public BigDecimal getDeservelyWage() {
		return this.deservelyWage;
	}

	public void setDeservelyWage(BigDecimal deservelyWage) {
		this.deservelyWage = deservelyWage;
	}

	public String getWageRewark() {
		return this.wageRewark;
	}

	public void setWageRewark(String wageRewark) {
		this.wageRewark = wageRewark;
	}

	public char getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(char delStatus) {
		this.delStatus = delStatus;
	}

	public BigDecimal getBascWage() {
		return this.bascWage;
	}

	public void setBascWage(BigDecimal bascWage) {
		this.bascWage = bascWage;
	}

}
